#!/usr/bin/env bash
# deploy/setup.sh — bootstrap a fresh host for gondor.
#
# Usage (run from this gondor checkout):
#
#   sudo ./deploy/setup.sh
#
# Idempotent: safe to re-run. Reads pinned versions from this script's
# top, the gondor app files from the cwd checkout, and writes:
#
#   /usr/local/bin/{assay,assay-engine}        runtime + engine binaries
#   /etc/gondor/{brand,pages,services,...}     app root
#   /etc/gondor-engine/engine.toml             engine config
#   /var/lib/gondor                            app data (audit log)
#   /var/lib/gondor-engine                     engine sqlite
#   /opt/assay/libs/hostops                    upstream lib via assay install
#   /etc/systemd/system/gondor*.service        systemd units
#
# Front the resulting :8080 (gondor) and :8082 (engine) with cloudflared
# or Traefik to expose them. Public hostnames live in the brand pack
# (see brand/brand.json) and ENGINE_BASE_URL in /etc/gondor/env.

set -euo pipefail

# ── pinned upstream versions ──────────────────────────────────────────
ASSAY_LUA_VERSION="${ASSAY_LUA_VERSION:-0.15.9}"
ASSAY_ENGINE_VERSION="${ASSAY_ENGINE_VERSION:-0.4.2}"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (use sudo)" >&2
  exit 1
fi

# ── platform detect ───────────────────────────────────────────────────
case "$(uname -s)" in
  Linux)  os=linux ;;
  Darwin) os=darwin ;;
  *)      echo "unsupported OS $(uname -s)" >&2; exit 1 ;;
esac
arch="$(uname -m)"
[[ "$arch" == "arm64" ]] && arch="aarch64"
ASSAY_ASSET="assay-${os}-${arch}"
ENGINE_ASSET="assay-engine-${os}-${arch}"

echo "=== gondor host bootstrap ==="
printf "  repo:               %s\n" "$REPO"
printf "  assay-lua:          %s (%s)\n" "$ASSAY_LUA_VERSION" "$ASSAY_ASSET"
printf "  assay-engine:       %s (%s)\n" "$ASSAY_ENGINE_VERSION" "$ENGINE_ASSET"
echo

# ── 1. binaries ───────────────────────────────────────────────────────
echo "[1/9] download assay $ASSAY_LUA_VERSION + assay-engine $ASSAY_ENGINE_VERSION"
curl -fsSL -o /tmp/assay.new \
  "https://github.com/developerinlondon/assay/releases/download/assay-lua-v${ASSAY_LUA_VERSION}/${ASSAY_ASSET}"
curl -fsSL -o /tmp/assay-engine.new \
  "https://github.com/developerinlondon/assay/releases/download/assay-engine-v${ASSAY_ENGINE_VERSION}/${ENGINE_ASSET}"
install -m 755 /tmp/assay.new        /usr/local/bin/assay
install -m 755 /tmp/assay-engine.new /usr/local/bin/assay-engine
rm -f /tmp/assay.new /tmp/assay-engine.new

# ── 2. service account ────────────────────────────────────────────────
echo "[2/9] gondor system user"
id gondor &>/dev/null \
  || useradd --system --create-home --shell /usr/sbin/nologin gondor

# ── 3. directory layout ───────────────────────────────────────────────
echo "[3/9] /etc/gondor + /var/lib/gondor* + /opt/assay/libs"
mkdir -p /etc/gondor /etc/gondor-engine \
         /var/lib/gondor /var/lib/gondor-engine \
         /opt/assay/libs
chown -R gondor:gondor /etc/gondor /etc/gondor-engine \
                       /var/lib/gondor /var/lib/gondor-engine \
                       /opt/assay

# ── 4. lay down runtime files from this checkout ──────────────────────
echo "[4/9] rsync runtime files into /etc/gondor"
rsync -a --delete "$REPO/brand/"     /etc/gondor/brand/
rsync -a --delete "$REPO/pages/"     /etc/gondor/pages/
rsync -a --delete "$REPO/services/"  /etc/gondor/services/
rsync -a --delete "$REPO/templates/" /etc/gondor/templates/
rsync -a --delete "$REPO/scripts/"   /etc/gondor/scripts/
rsync -a --delete "$REPO/static/"    /etc/gondor/static/
install -m 644 "$REPO/Manifest.lua" /etc/gondor/Manifest.lua
install -m 644 "$REPO/VERSION"      /etc/gondor/VERSION

# ── 5. /etc/gondor/env ────────────────────────────────────────────────
echo "[5/9] /etc/gondor/env"
if [[ ! -f /etc/gondor/env ]]; then
  ADMIN_KEY=$(openssl rand -hex 32)
  cat > /etc/gondor/env <<ENVEOF
# Generated by deploy/setup.sh on first install. Edit as needed.
# See deploy/env.example for the full set of supported variables.

GONDOR_ADMIN_API_KEYS=${ADMIN_KEY}
ENGINE_URL=http://127.0.0.1:8082
# Public engine subdomain — needs a cloudflared / Traefik route pointing
# at 127.0.0.1:8082 for the "Open in engine ↗" buttons to actually work.
# Override via env on first install (see header comment above).
ENGINE_BASE_URL=${ENGINE_BASE_URL:-https://gondor-engine.fcar.ai}
HOSTOPS_LIB_ROOT=/opt/assay/libs/hostops
GONDOR_ROOT=/etc/gondor
BRAND_DIR=/etc/gondor/brand
PORT=8080
WORKFLOW_NAMESPACE=main
AUDIT_PATH=/var/lib/gondor/audit.log
LUA_PATH=/opt/assay/libs/?.lua;/opt/assay/libs/?/init.lua;/opt/assay/libs/hostops/?.lua;/etc/gondor/?.lua;/etc/gondor/?/init.lua;;
ENVEOF
  echo "  wrote new /etc/gondor/env (with fresh admin key)"
else
  echo "  exists — leaving alone (edit manually if needed)"
fi
chown root:gondor /etc/gondor/env
chmod 640         /etc/gondor/env
chown -R gondor:gondor /etc/gondor

# ── 6. /etc/gondor-engine/engine.toml ─────────────────────────────────
echo "[6/9] /etc/gondor-engine/engine.toml"
if [[ ! -f /etc/gondor-engine/engine.toml ]]; then
  install -m 644 "$REPO/deploy/engine.toml.example" /etc/gondor-engine/engine.toml
  echo "  copied template"
else
  echo "  exists — leaving alone (edit manually if needed)"
fi
chown gondor:gondor /etc/gondor-engine/engine.toml

# ── 7. assay install (libs) + flatten doubled-nest ────────────────────
echo "[7/9] assay install (hostops + any other libs from Manifest.lua)"
sudo -u gondor bash -c "
  set -euo pipefail
  cd /etc/gondor
  set -a; . /etc/gondor/env; set +a
  /usr/local/bin/assay install --manifest Manifest.lua --lib-dir /opt/assay/libs
"

# Workaround: the assay-lib-*.tar.gz tarballs published by the assay
# release pipeline contain a top-level <libname>/ directory, AND
# `assay install` also wraps the extract target in <libname>/ — so
# files end up at /opt/assay/libs/<libname>/<libname>/<files>. Flatten
# the inner dir so `require("<libname>.foo")` resolves at the expected
# /opt/assay/libs/<libname>/foo.lua path.
for libdir in /opt/assay/libs/*/; do
  libname="$(basename "$libdir")"
  inner="${libdir}${libname}"
  if [[ -d "$inner" ]]; then
    shopt -s dotglob nullglob
    mv "$inner"/* "$libdir"
    rmdir "$inner"
    shopt -u dotglob nullglob
    echo "  flattened nested $libname (workaround for upstream tarball packaging)"
  fi
done

# ── 8. systemd units ──────────────────────────────────────────────────
echo "[8/9] systemd units"
install -m 644 "$REPO/deploy/gondor.service.example"        /etc/systemd/system/gondor.service
install -m 644 "$REPO/deploy/gondor-engine.service.example" /etc/systemd/system/gondor-engine.service
systemctl daemon-reload

# ── 9. enable + start + verify ────────────────────────────────────────
echo "[9/9] enable + start"
systemctl enable --now gondor-engine.service gondor.service
sleep 4

echo
echo "=== verify ==="
echo "active states:"
systemctl is-active gondor-engine.service gondor.service
echo "ports listening:"
ss -tlnp 2>/dev/null | grep -E ':(8080|8082)' | head -5 || true
echo "healthz:"
curl -s -m 5 http://127.0.0.1:8080/healthz; echo

echo
echo "Done. Visit http://127.0.0.1:8080/ (or your reverse-proxy front)."
echo "Edit /etc/gondor/env if you need to swap PORT / ENGINE_BASE_URL /"
echo "GONDOR_ADMIN_API_KEYS, then 'systemctl restart gondor gondor-engine'."
